def constants_print():
    return ('LAYER_SIZE '+str('%.1f'%LAYER_SIZE)+ '\nAVERAGE_HEAT_CAPACITY '+str('%.1f'%AVERAGE_HEAT_CAPACITY)
            + '\nTHERMAL_CONDUCTIVITY '+str('%.1f'%THERMAL_CONDUCTIVITY)+ '\nWATER_LATENT_HEAT_PERCENTAGE_COEFFICIENT '+str('%.1f'%WATER_LATENT_HEAT_PERCENTAGE_COEFFICIENT)
            + '\nINITIAL_EARTH_TEMPERATURE '+str('%.1f'%INITIAL_EARTH_TEMPERATURE)+ '\nSOLAR_CONSTANT '+str('%.1f'%SOLAR_CONSTANT)
            + '\nATMOSPHERE_REFLECTED_COEFFICIENT '+str('%.1f'%ATMOSPHERE_REFLECTED_COEFFICIENT)+ '\nGREEN_HOUSE_EFFECT_COEFFICIENT '+str('%.1f'%GREEN_HOUSE_EFFECT_COEFFICIENT)
            + '\nCLOUD_ALBEDO '+str('%.1f'%CLOUD_ALBEDO)+'\n')
EARTH_RADIUS = 6367444.7
LAYER_SIZE = 6367444.7
AVERAGE_HEAT_CAPACITY = 5.3e8 * (1 - (1 - LAYER_SIZE / EARTH_RADIUS) ** 3)
THERMAL_CONDUCTIVITY = 5e6
WATER_LATENT_HEAT_PERCENTAGE_COEFFICIENT = 334000*100
MELTING_POINT = 273.15
INITIAL_EARTH_TEMPERATURE = 0

SOLAR_CONSTANT = 1367
ATMOSPHERE_REFLECTED_COEFFICIENT = 0.1  # zwiazwiane z gazami atmosfery ale nie z zachmurzeniem
GREEN_HOUSE_EFFECT_COEFFICIENT = 0.4
STEFAN_BOLTZMAN_CONSTANT = 5.670e-8
CLOUD_ALBEDO = 0.8

START_YEAR = 0
END_YEAR = 1000